// <auto-generated />
using DogsAdoptionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogsAdoptionService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogsAdoptionService.Models.DogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cuteness")
                        .HasColumnType("int");

                    b.Property<string>("FavFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavToy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdopted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Temperament")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cuteness = 10,
                            FavFood = "Barkoni",
                            FavToy = "Barkle",
                            Image = "BarkTwain1.jpg",
                            IsAdopted = false,
                            Name = "Bark Twain",
                            Temperament = 7
                        },
                        new
                        {
                            Id = 2,
                            Cuteness = 10,
                            FavFood = "Pawsta",
                            FavToy = "Fetch Stick",
                            Image = "SirWaggington2.jpg",
                            IsAdopted = false,
                            Name = "Sir Waggington",
                            Temperament = 6
                        },
                        new
                        {
                            Id = 3,
                            Cuteness = 10,
                            FavFood = "Bone Appetit",
                            FavToy = "Squeaky Ball",
                            Image = "Furball3.jpg",
                            IsAdopted = false,
                            Name = "Furball",
                            Temperament = 8
                        },
                        new
                        {
                            Id = 4,
                            Cuteness = 10,
                            FavFood = "Royal Canin",
                            FavToy = "Diamond Collar",
                            Image = "PrincessPaws4.jpg",
                            IsAdopted = false,
                            Name = "Princess Paws",
                            Temperament = 6
                        },
                        new
                        {
                            Id = 5,
                            Cuteness = 10,
                            FavFood = "Pupcakes",
                            FavToy = "Chewy Bone",
                            Image = "Biscuit5.jpg",
                            IsAdopted = false,
                            Name = "Biscuit",
                            Temperament = 9
                        },
                        new
                        {
                            Id = 6,
                            Cuteness = 10,
                            FavFood = "Doggie Delight",
                            FavToy = "Plush Squirrel",
                            Image = "Daisy6.jpg",
                            IsAdopted = false,
                            Name = "Daisy",
                            Temperament = 6
                        },
                        new
                        {
                            Id = 7,
                            Cuteness = 10,
                            FavFood = "Fish 'n Chips",
                            FavToy = "Nautical Rope",
                            Image = "CaptainWoof7.jpg",
                            IsAdopted = false,
                            Name = "Captain Woof",
                            Temperament = 8
                        },
                        new
                        {
                            Id = 8,
                            Cuteness = 10,
                            FavFood = "Cuddle Crunchies",
                            FavToy = "Soft Blanket",
                            Image = "SnugglePaws8.jpg",
                            IsAdopted = false,
                            Name = "Snuggle Paws",
                            Temperament = 7
                        },
                        new
                        {
                            Id = 9,
                            Cuteness = 10,
                            FavFood = "Steak Bites",
                            FavToy = "Tennis Ball",
                            Image = "Rocky9.jpg",
                            IsAdopted = false,
                            Name = "Rocky",
                            Temperament = 7
                        },
                        new
                        {
                            Id = 10,
                            Cuteness = 10,
                            FavFood = "Treat Tower",
                            FavToy = "Squeaky Duck",
                            Image = "Lola10.jpg",
                            IsAdopted = false,
                            Name = "Lola",
                            Temperament = 6
                        },
                        new
                        {
                            Id = 11,
                            Cuteness = 10,
                            FavFood = "Beefy Bites",
                            FavToy = "Tug Rope",
                            Image = "Maximus11.jpg",
                            IsAdopted = false,
                            Name = "Maximus",
                            Temperament = 9
                        },
                        new
                        {
                            Id = 12,
                            Cuteness = 10,
                            FavFood = "Chicken Chewies",
                            FavToy = "Frisbee",
                            Image = "Roxy12.jpg",
                            IsAdopted = false,
                            Name = "Roxy",
                            Temperament = 7
                        },
                        new
                        {
                            Id = 13,
                            Cuteness = 10,
                            FavFood = "Carrot Crunch",
                            FavToy = "Plush Bunny",
                            Image = "Teddy13.jpg",
                            IsAdopted = false,
                            Name = "Teddy",
                            Temperament = 6
                        },
                        new
                        {
                            Id = 14,
                            Cuteness = 10,
                            FavFood = "Coconut Chew",
                            FavToy = "Ball Launcher",
                            Image = "Coco14.jpg",
                            IsAdopted = false,
                            Name = "Coco",
                            Temperament = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
